# Generated by Django 3.1 on 2020-08-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time_zone',
            new_name='tz',
        ),
    ]
